import type { INodePropertyOptions } from 'n8n-workflow';

export const getCountryOptions = (): INodePropertyOptions[] => [
    { name: 'United States - US', value: 'US' },
    { name: 'Canada - CA', value: 'CA' },
    { name: 'Afghanistan - AF', value: 'AF' },
    { name: 'Åland Islands - AX', value: 'AX' },
    { name: 'Albania - AL', value: 'AL' },
    { name: 'Algeria - DZ', value: 'DZ' },
    { name: 'American Samoa - AS', value: 'AS' },
    { name: 'Andorra - AD', value: 'AD' },
    { name: 'Angola - AO', value: 'AO' },
    { name: 'Anguilla - AI', value: 'AI' },
    { name: 'Antarctica - AQ', value: 'AQ' },
    { name: 'Antigua and Barbuda - AG', value: 'AG' },
    { name: 'Argentina - AR', value: 'AR' },
    { name: 'Armenia - AM', value: 'AM' },
    { name: 'Aruba - AW', value: 'AW' },
    { name: 'Australia - AU', value: 'AU' },
    { name: 'Austria - AT', value: 'AT' },
    { name: 'Azerbaijan - AZ', value: 'AZ' },
    { name: 'Bahamas - BS', value: 'BS' },
    { name: 'Bahrain - BH', value: 'BH' },
    { name: 'Bangladesh - BD', value: 'BD' },
    { name: 'Barbados - BB', value: 'BB' },
    { name: 'Belarus - BY', value: 'BY' },
    { name: 'Belgium - BE', value: 'BE' },
    { name: 'Belize - BZ', value: 'BZ' },
    { name: 'Benin - BJ', value: 'BJ' },
    { name: 'Bermuda - BM', value: 'BM' },
    { name: 'Bhutan - BT', value: 'BT' },
    { name: 'Bolivia - BO', value: 'BO' },
    { name: 'Bonaire, Sint Eustatius and Saba - BQ', value: 'BQ' },
    { name: 'Bosnia and Herzegovina - BA', value: 'BA' },
    { name: 'Botswana - BW', value: 'BW' },
    { name: 'Bouvet Island - BV', value: 'BV' },
    { name: 'Brazil - BR', value: 'BR' },
    { name: 'British Indian Ocean Territory - IO', value: 'IO' },
    { name: 'Brunei Darussalam - BN', value: 'BN' },
    { name: 'Bulgaria - BG', value: 'BG' },
    { name: 'Burkina Faso - BF', value: 'BF' },
    { name: 'Burundi - BI', value: 'BI' },
    { name: 'Cabo Verde - CV', value: 'CV' },
    { name: 'Cambodia - KH', value: 'KH' },
    { name: 'Cameroon - CM', value: 'CM' },
    { name: 'Central African Republic - CF', value: 'CF' },
    { name: 'Chad - TD', value: 'TD' },
    { name: 'Chile - CL', value: 'CL' },
    { name: 'China - CN', value: 'CN' },
    { name: 'Christmas Island - CX', value: 'CX' },
    { name: 'Cocos (Keeling) Islands - CC', value: 'CC' },
    { name: 'Colombia - CO', value: 'CO' },
    { name: 'Comoros - KM', value: 'KM' },
    { name: 'Congo - CG', value: 'CG' },
    { name: 'Congo, Democratic Republic of the - CD', value: 'CD' },
    { name: 'Cook Islands - CK', value: 'CK' },
    { name: 'Costa Rica - CR', value: 'CR' },
    { name: 'Côte d\'Ivoire - CI', value: 'CI' },
    { name: 'Croatia - HR', value: 'HR' },
    { name: 'Cuba - CU', value: 'CU' },
    { name: 'Curaçao - CW', value: 'CW' },
    { name: 'Cyprus - CY', value: 'CY' },
    { name: 'Czechia - CZ', value: 'CZ' },
    { name: 'Denmark - DK', value: 'DK' },
    { name: 'Djibouti - DJ', value: 'DJ' },
    { name: 'Dominica - DM', value: 'DM' },
    { name: 'Dominican Republic - DO', value: 'DO' },
    { name: 'Ecuador - EC', value: 'EC' },
    { name: 'Egypt - EG', value: 'EG' },
    { name: 'El Salvador - SV', value: 'SV' },
    { name: 'Equatorial Guinea - GQ', value: 'GQ' },
    { name: 'Eritrea - ER', value: 'ER' },
    { name: 'Estonia - EE', value: 'EE' },
    { name: 'Eswatini - SZ', value: 'SZ' },
    { name: 'Ethiopia - ET', value: 'ET' },
    { name: 'Falkland Islands (Malvinas) - FK', value: 'FK' },
    { name: 'Faroe Islands - FO', value: 'FO' },
    { name: 'Fiji - FJ', value: 'FJ' },
    { name: 'Finland - FI', value: 'FI' },
    { name: 'France - FR', value: 'FR' },
    { name: 'French Guiana - GF', value: 'GF' },
    { name: 'French Polynesia - PF', value: 'PF' },
    { name: 'French Southern Territories - TF', value: 'TF' },
    { name: 'Gabon - GA', value: 'GA' },
    { name: 'Gambia - GM', value: 'GM' },
    { name: 'Georgia - GE', value: 'GE' },
    { name: 'Germany - DE', value: 'DE' },
    { name: 'Ghana - GH', value: 'GH' },
    { name: 'Gibraltar - GI', value: 'GI' },
    { name: 'Greece - GR', value: 'GR' },
    { name: 'Greenland - GL', value: 'GL' },
    { name: 'Grenada - GD', value: 'GD' },
    { name: 'Guadeloupe - GP', value: 'GP' },
    { name: 'Guam - GU', value: 'GU' },
    { name: 'Guatemala - GT', value: 'GT' },
    { name: 'Guernsey - GG', value: 'GG' },
    { name: 'Guinea - GN', value: 'GN' },
    { name: 'Guinea-Bissau - GW', value: 'GW' },
    { name: 'Guyana - GY', value: 'GY' },
    { name: 'Haiti - HT', value: 'HT' },
    { name: 'Heard Island and McDonald Islands - HM', value: 'HM' },
    { name: 'Holy See - VA', value: 'VA' },
    { name: 'Honduras - HN', value: 'HN' },
    { name: 'Hong Kong - HK', value: 'HK' },
    { name: 'Hungary - HU', value: 'HU' },
    { name: 'Iceland - IS', value: 'IS' },
    { name: 'India - IN', value: 'IN' },
    { name: 'Indonesia - ID', value: 'ID' },
    { name: 'Iran - IR', value: 'IR' },
    { name: 'Iraq - IQ', value: 'IQ' },
    { name: 'Ireland - IE', value: 'IE' },
    { name: 'Isle of Man - IM', value: 'IM' },
    { name: 'Israel - IL', value: 'IL' },
    { name: 'Italy - IT', value: 'IT' },
    { name: 'Jamaica - JM', value: 'JM' },
    { name: 'Japan - JP', value: 'JP' },
    { name: 'Jersey - JE', value: 'JE' },
    { name: 'Jordan - JO', value: 'JO' },
    { name: 'Kazakhstan - KZ', value: 'KZ' },
    { name: 'Kenya - KE', value: 'KE' },
    { name: 'Kiribati - KI', value: 'KI' },
    { name: 'Korea (Democratic People\'s Republic of) - KP', value: 'KP' },
    { name: 'Korea (Republic of) - KR', value: 'KR' },
    { name: 'Kuwait - KW', value: 'KW' },
    { name: 'Kyrgyzstan - KG', value: 'KG' },
    { name: 'Lao People\'s Democratic Republic - LA', value: 'LA' },
    { name: 'Latvia - LV', value: 'LV' },
    { name: 'Lebanon - LB', value: 'LB' },
    { name: 'Lesotho - LS', value: 'LS' },
    { name: 'Liberia - LR', value: 'LR' },
    { name: 'Libya - LY', value: 'LY' },
    { name: 'Liechtenstein - LI', value: 'LI' },
    { name: 'Lithuania - LT', value: 'LT' },
    { name: 'Luxembourg - LU', value: 'LU' },
    { name: 'Macao - MO', value: 'MO' },
    { name: 'Madagascar - MG', value: 'MG' },
    { name: 'Malawi - MW', value: 'MW' },
    { name: 'Malaysia - MY', value: 'MY' },
    { name: 'Maldives - MV', value: 'MV' },
    { name: 'Mali - ML', value: 'ML' },
    { name: 'Malta - MT', value: 'MT' },
    { name: 'Marshall Islands - MH', value: 'MH' },
    { name: 'Martinique - MQ', value: 'MQ' },
    { name: 'Mauritania - MR', value: 'MR' },
    { name: 'Mauritius - MU', value: 'MU' },
    { name: 'Mayotte - YT', value: 'YT' },
    { name: 'Mexico - MX', value: 'MX' },
    { name: 'Micronesia (Federated States of) - FM', value: 'FM' },
    { name: 'Moldova - MD', value: 'MD' },
    { name: 'Monaco - MC', value: 'MC' },
    { name: 'Mongolia - MN', value: 'MN' },
    { name: 'Montenegro - ME', value: 'ME' },
    { name: 'Montserrat - MS', value: 'MS' },
    { name: 'Morocco - MA', value: 'MA' },
    { name: 'Mozambique - MZ', value: 'MZ' },
    { name: 'Myanmar - MM', value: 'MM' },
    { name: 'Namibia - NA', value: 'NA' },
    { name: 'Nauru - NR', value: 'NR' },
    { name: 'Nepal - NP', value: 'NP' },
    { name: 'Netherlands - NL', value: 'NL' },
    { name: 'New Caledonia - NC', value: 'NC' },
    { name: 'New Zealand - NZ', value: 'NZ' },
    { name: 'Nicaragua - NI', value: 'NI' },
    { name: 'Niger - NE', value: 'NE' },
    { name: 'Nigeria - NG', value: 'NG' },
    { name: 'Niue - NU', value: 'NU' },
    { name: 'Norfolk Island - NF', value: 'NF' },
    { name: 'North Macedonia - MK', value: 'MK' },
    { name: 'Northern Mariana Islands - MP', value: 'MP' },
    { name: 'Norway - NO', value: 'NO' },
    { name: 'Oman - OM', value: 'OM' },
    { name: 'Pakistan - PK', value: 'PK' },
    { name: 'Palau - PW', value: 'PW' },
    { name: 'Palestine, State of - PS', value: 'PS' },
    { name: 'Panama - PA', value: 'PA' },
    { name: 'Papua New Guinea - PG', value: 'PG' },
    { name: 'Paraguay - PY', value: 'PY' },
    { name: 'Peru - PE', value: 'PE' },
    { name: 'Philippines - PH', value: 'PH' },
    { name: 'Pitcairn - PN', value: 'PN' },
    { name: 'Poland - PL', value: 'PL' },
    { name: 'Portugal - PT', value: 'PT' },
    { name: 'Puerto Rico - PR', value: 'PR' },
    { name: 'Qatar - QA', value: 'QA' },
    { name: 'Réunion - RE', value: 'RE' },
    { name: 'Romania - RO', value: 'RO' },
    { name: 'Russian Federation - RU', value: 'RU' },
    { name: 'Rwanda - RW', value: 'RW' },
    { name: 'Saint Barthélemy - BL', value: 'BL' },
    { name: 'Saint Helena, Ascension and Tristan Da Cunha - SH', value: 'SH' },
    { name: 'Saint Kitts and Nevis - KN', value: 'KN' },
    { name: 'Saint Lucia - LC', value: 'LC' },
    { name: 'Saint Martin (French Part) - MF', value: 'MF' },
    { name: 'Saint Pierre and Miquelon - PM', value: 'PM' },
    { name: 'Saint Vincent and the Grenadines - VC', value: 'VC' },
    { name: 'Samoa - WS', value: 'WS' },
    { name: 'San Marino - SM', value: 'SM' },
    { name: 'Sao Tome and Principe - ST', value: 'ST' },
    { name: 'Saudi Arabia - SA', value: 'SA' },
    { name: 'Senegal - SN', value: 'SN' },
    { name: 'Serbia - RS', value: 'RS' },
    { name: 'Seychelles - SC', value: 'SC' },
    { name: 'Sierra Leone - SL', value: 'SL' },
    { name: 'Singapore - SG', value: 'SG' },
    { name: 'Sint Maarten (Dutch Part) - SX', value: 'SX' },
    { name: 'Slovakia - SK', value: 'SK' },
    { name: 'Slovenia - SI', value: 'SI' },
    { name: 'Solomon Islands - SB', value: 'SB' },
    { name: 'Somalia - SO', value: 'SO' },
    { name: 'South Africa - ZA', value: 'ZA' },
    { name: 'South Georgia and the South Sandwich Islands - GS', value: 'GS' },
    { name: 'South Sudan - SS', value: 'SS' },
    { name: 'Spain - ES', value: 'ES' },
    { name: 'Sri Lanka - LK', value: 'LK' },
    { name: 'Sudan - SD', value: 'SD' },
    { name: 'Suriname - SR', value: 'SR' },
    { name: 'Svalbard and Jan Mayen - SJ', value: 'SJ' },
    { name: 'Sweden - SE', value: 'SE' },
    { name: 'Switzerland - CH', value: 'CH' },
    { name: 'Syrian Arab Republic - SY', value: 'SY' },
    { name: 'Taiwan - TW', value: 'TW' },
    { name: 'Tajikistan - TJ', value: 'TJ' },
    { name: 'Tanzania, United Republic of - TZ', value: 'TZ' },
    { name: 'Thailand - TH', value: 'TH' },
    { name: 'Timor-Leste - TL', value: 'TL' },
    { name: 'Togo - TG', value: 'TG' },
    { name: 'Tokelau - TK', value: 'TK' },
    { name: 'Tonga - TO', value: 'TO' },
    { name: 'Trinidad and Tobago - TT', value: 'TT' },
    { name: 'Tunisia - TN', value: 'TN' },
    { name: 'Turkey - TR', value: 'TR' },
    { name: 'Turkmenistan - TM', value: 'TM' },
    { name: 'Turks and Caicos Islands - TC', value: 'TC' },
    { name: 'Tuvalu - TV', value: 'TV' },
    { name: 'Uganda - UG', value: 'UG' },
    { name: 'Ukraine - UA', value: 'UA' },
    { name: 'United Arab Emirates - AE', value: 'AE' },
    { name: 'United Kingdom - GB', value: 'GB' },
    { name: 'United States Minor Outlying Islands - UM', value: 'UM' },
    { name: 'Uruguay - UY', value: 'UY' },
    { name: 'Uzbekistan - UZ', value: 'UZ' },
    { name: 'Vanuatu - VU', value: 'VU' },
    { name: 'Venezuela - VE', value: 'VE' },
    { name: 'Viet Nam - VN', value: 'VN' },
    { name: 'Virgin Islands (British) - VG', value: 'VG' },
    { name: 'Virgin Islands (U.S.) - VI', value: 'VI' },
    { name: 'Wallis and Futuna - WF', value: 'WF' },
    { name: 'Western Sahara - EH', value: 'EH' },
    { name: 'Yemen - YE', value: 'YE' },
    { name: 'Zambia - ZM', value: 'ZM' },
    { name: 'Zimbabwe - ZW', value: 'ZW' },
];
